export default {
  updating: "Updating",
  update: "Update",
  updated: "Updated",
  updating_data: "Updating data",
  api_error_message: "Error. Could not update due to issues with the Riot Games API.",
  available_in: "Available in",
  seconds: "seconds",
  info_message_1: "Position changes are restored at 00:00 GMT-6.",
  ago: "ago",
  accounts: "accounts",
  lang: "Language",
  english: "English",
  spanish: "Spanish",
  rank: "Rank",
  position_change: "Position change",
  is_live: "Live",
  streamer: "Streamer",
  instagram: "Instagram",
  twitter: "Twitter X",
  is_ingame: "Ingame",
  account: "Account",
  region: "Region",
  elo: "Elo",
  matches: "Matches",
  v_d: "W - L",
  winrate: "Winrate",
  live_em: "Live!",
  ingame_em: "Ingame!",
  minute: "minute",
  second: "second",
  day: "day",
  month: "month",
  year: "year",
  minutes: "minutes",
  days: "days",
  months: "months",
  years: "years",
  hour: "hour",
  hours: "hours",
  developed_by: "Developed by",
  home: "Home",
  w: "W",
  l: "L",
  at_least: "at least",
  games_played: "games played",
  kda_averages: "KDA Averages",
  highest: "Highest",
  lowest: "Lowest",
  champion_winrates: "Champion Winrates"
};