export default {
  updating: "Actualizando",
  update: "Actualizar",
  updated: "Actualizado",
  updating_data: "Actualizando los datos",
  api_error_message: "Error. No se ha podido actualizar debido a problemas con el API de Riot Games.",
  available_in: "Disponible en",
  seconds: "segundos",
  info_message_1: "Los cambios de posición se restauran a las 00:00 GMT-6.",
  ago: "hace",
  accounts: "cuentas",
  lang: "Idioma",
  english: "Inglés",
  spanish: "Español",
  rank: "Posición",
  position_change: "Cambio de posición",
  is_live: "En vivo",
  streamer: "Streamer",
  instagram: "Instagram",
  twitter: "Twitter X",
  is_ingame: "En partida",
  account: "Cuenta",
  region: "Región",
  elo: "Elo",
  matches: "Partidas",
  v_d: "V - D",
  winrate: "Winrate",
  live_em: "¡En vivo!",
  ingame_em: "¡En partida!",
  minute: "minuto",
  second: "segundo",
  day: "día",
  month: "mes",
  year: "año",
  minutes: "minutos",
  days: "días",
  months: "meses",
  years: "años",
  hour: "hora",
  hours: "horas",
  developed_by: "Desarrollado por",
  home: "Inicio",
  w: "V",
  l: "D",
  at_least: "al menos",
  games_played: "partidas jugadas",
  kda_averages: "Promedios KDA",
  highest: "Mejores",
  lowest: "Peores",
  champion_winrates: "Winrates de campeón",
  duration: "Duración",
  games: "Partidas",
  longest: "Más Largas",
  shortest: "Más Cortas",
  excluding_surrenders: "excluyendo partidas terminadas en surrender"
};