name = "streamers-ladder"
main = "src/index.js"
compatibility_date = "2024-04-24"

[[d1_databases]]
binding = "PARTICIPANTS"
database_name = "streamers-ladder"
database_id = "f9bc299b-450d-437f-aa57-ea8934841989"

[triggers]
crons = ["0 6 * * *"]