name = "streamers-ladder"
main = "src/index.js"
compatibility_date = "2024-04-24"

tail_consumers = [{service = "streamers-ladder"}]

[[d1_databases]]
binding = "PARTICIPANTS"
database_name = "streamers-ladder"
database_id = "f9bc299b-450d-437f-aa57-ea8934841989"

[triggers]
crons = [
  "0 6 * * *", # reset position change (1 AM | GMT-5)
  "0 5/12 * * *", #las every 12 hours starting at 12 AM (GMT-5)
  "0 4/12 * * *", #na every 12 hours starting at 11 PM (GMT-5)
  "0 3/12 * * *", #euw every 12 hours starting at 10 PM (GMT-5)
  "0 2/12 * * *", #lan every 12 hours starting at 9 PM (GMT-5)
]

[placement]
mode = "smart"